# This is a basic workflow to help you get started with Actions

name: CI

on:
  schedule:
    - cron:  '0 * * * *'
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: yosupo06/library-checker-problems
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64'
    - name: ci
      run: |
        pip3 install -r requirements.txt
        ulimit -s unlimited
        ./generate.py -p unionfind
    - name: Deploy website
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build

